Update build-cloud-gov.yml

diff --git a/.github/workflows/build-cloud-gov.yml b/.github/workflows/build-cloud-gov.yml
--- a/.github/workflows/build-cloud-gov.yml
+++ b/.github/workflows/build-cloud-gov.yml
@@ -1,9 +1,12 @@
+name: Copy R Shiny app to cloud-gov branch and request push to dev
+
 on:
   workflow_dispatch:
     inputs:
       build_deps:
         description: 'Also build R dependencies?'
         required: true
+        default: true
         type: boolean
 
 permissions:
@@ -75,7 +78,8 @@ jobs:
     - name: Setup R
       uses: r-lib/actions/setup-r@v2
       with:
-        r-version: 4.2.2
+        r-version: 4.3.1
+        use-public-rspm: true
 
     - name: Setup pandoc
       uses: r-lib/actions/setup-pandoc@v2
@@ -86,6 +90,7 @@ jobs:
         packages: |
           stringr
           devtools
+          rlist
           sf
 
     - name: List R dependencies
@@ -95,19 +100,20 @@ jobs:
     - name: Download R packages
       run: |
         if [ -d "vendor_r" ]; then rm -fr vendor_r; fi
-        if [ -f "r-github-actions-build-deps.txt" ]; then rm r-github-actions-build-deps.txt; fi
         Rscript scripts/download_packages.R vendor_r/src/contrib ${{ env.packs }}
-        more r-github-actions-build-deps.txt
-        if [ `grep sf r-github-actions-build-deps.txt | wc -c` -gt 0 ]; then echo needs_geo=true; else echo needs_geo=false; fi >> $GITHUB_ENV
-        if [ `grep pandoc r-github-actions-build-deps.txt | wc -c` -gt 0 ]; then echo needs_pandoc=true; else echo needs_pandoc=false; fi >> $GITHUB_ENV
-        # if [ -f "r-github-actions-build-deps.txt" ]; then echo needs_libraries=true; else echo needs_libraries=false; fi >> $GITHUB_ENV
+        cd vendor_r/src/contrib
+        if ls sf_* >/dev/null 2>&1; then echo needs_geo=true; else echo needs_geo=false; fi >> $GITHUB_ENV
+        if ls rmarkdown_* >/dev/null 2>&1; then echo needs_pandoc=true; else echo needs_pandoc=false; fi >> $GITHUB_ENV
+        if ls *_R_x86_64-pc-linux-gnu.tar.gz >/dev/null 2>&1; then 
+          find -name '*_R_x86_64-pc-linux-gnu.tar.gz' -print0 | sed -ze "p;s/\_R_x86_64-pc-linux-gnu//" | xargs -0 -n2 mv;
+        fi
+        cd ../../..
+      env: 
+        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
 
     - name: Run lib_tar.sh to extract each of the libraries needed by sf
       if: ${{ env.needs_geo == 'true' }}
       run: |
-        cd vendor_r/src/contrib
-        find -name '*_R_x86_64-pc-linux-gnu.tar.gz' -print0 | sed -ze "p;s/\_R_x86_64-pc-linux-gnu//" | xargs -0 -n2 mv
-        cd ../../..
         if [ -d "r-lib" ]; then rm -fr r-lib; fi
         mkdir r-lib
         chmod +x scripts/lib_tar.sh
@@ -130,7 +136,7 @@ jobs:
         
     - name: Add additional files to repo if not already there
       run: |
-        if [ ! ls "manifest*.yml" 1> /dev/null 2>&1 ]; then
+        if ! ls manifest*.yml >/dev/null 2>&1; then
           mv scripts/include/manifest.yml .
           git add manifest.yml
         fi
@@ -149,3 +155,26 @@ jobs:
         git add vendor_r
         git diff-index --quiet HEAD || git commit -m "Automated workflow from GitHub Actions to vendor R dependencies"
         git push
+
+  request_copy:
+    # Note: this step will fail if OWSHINY_ACTION secret is not set up in the repo and should be removed
+    name: Request copy uploaded to deployment repo if permitted
+    needs: [copy_code_to_cloud-gov, download_and_vendor_dependencies]
+    if: always() && !contains(needs.*.result, 'failure')
+    # Needs to run even if download_and_vendor_dependencies was skipped
+    runs-on: ubuntu-latest
+    steps:
+      - name: Trigger Workflow to copy for deployment
+        uses: actions/github-script@v6
+        with:
+          github-token: ${{ secrets.OWSHINY_ACTION }}
+          script: |
+            github.rest.actions.createWorkflowDispatch({
+              owner: 'USEPA',
+              repo: 'OWShiny',
+              workflow_id: 'copy_repo.yml',
+              ref: 'develop',
+              inputs: {
+                "repo_to_copy": context.repo.owner + "/" + context.repo.repo
+              }
+            })
